version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_name: '@babel/*'
          update_type: 'semver:minor'
      - match:
          dependency_name: '@typescript-eslint/*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'prettier'
          update_type: 'all'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '13.x'
